# On a new commit: push new docs to anchorage-docs.github.io

name: Deploy docs

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  
  Deploy:

    runs-on: ubuntu-latest
    environment: alexandria-docs

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Install pdoc3
        run: pip install pdoc3
      - name: Check running directory
        run: |
          pwd
          ls
          cd alexandria
          ls
          cd ..
      - name: Generate docs
        run:  pdoc --html alexandria --force --output-dir=docs
      - name: Push new docs to anchorage-docs.github.io
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'docs/alexandria'
          destination-github-username: 'alopezrivera-docs'
          destination-repository-name: 'alexandria'
          user-email: alopezrivera.docs@gmail.com
          commit-message: See ORIGIN_COMMIT from $GITHUB_REF
          target-branch: main
